[package]
name = "bmm-lib"
version = "0.1.5"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
bincode = "1.3.3"
bytes = "1.10.0"
dirs = "6.0.0"
flate2 = { version = "1.1.0", features = ["zlib"] }
infer = "0.16.0"
libc = "0.2.170"
libflate = "2.1.0"
log = "0.4.26"
reqwest = { version = "0.12.12", features = ["json"] }
rusqlite = { version = "0.33.0", features = ["bundled"] }
serde = { version = "1.0.218", features = ["serde_derive"] }
serde_json = "1.0.139"
serde_repr = "0.1.19"
tar = "0.4.44"
tauri = "2.2.5"
tempfile = "3.17.1"
tokio = { version = "1.43.0", features = ["full"] }
zip = "2.2.2"

[dev-dependencies]
tempfile = "3.17.1"
scopeguard = "1.2.0"
mockito = "1.6.1"
tokio = { version = "1.43.0", features = ["full", "test-util"] }
rstest = "0.24.0"

[target.'cfg(windows)'.dependencies]
winreg = "0.52.0"
sysinfo = "0.33.1"

[target.'cfg(unix)'.dependencies]
libproc = "0.14.10"
home = "0.5.11"
libloading = "0.8.6"

[build-dependencies]
dirs = "6.0.0"
